#!/bin/sh

URL=""
SEPARATOR=","
FORMATTING="url uploader title"
TAGS=""
while [ "$#" -gt "0" ]; do
    case $1 in
        "-t") TAGS="$2" shift ;;
        "-s") SEPARATOR="$2" shift ;;
        "-f") FORMATTING="$2" shift ;;
        "-h") echo "todo help" ;;
        "-v") echo "todo version" ;;
        *) 
            if [ -n "`echo "$1" | grep "^-"`" ] || [ ! -z "$URL" ]; then
                echo "invalid command. Use ytpl -h for help" >&2; exit 1
            else
                URL="$1"
            fi
        ;;
    esac
    shift
done
#

#check if formatting is valid
for i in $FORMATTING; do
    case $i in 
        "url") : ;;
        "uploader") : ;;
        "title") : ;;
        "tags") : ;;
        *) 
            echo "invalid formatting string. Use ytpl -h for help" >&2; exit 2
        ;;
    esac
done

#transform the formatting string into something readable by jq
FORMATTING=`echo $FORMATTING | \
            sed 's/url/https\:\/\/youtu.be\/\\\(\.\[\"url\"\]\)/' | \
            sed 's/title/\\\\(\.\[\"title\"\]\)/' | \
            sed 's/uploader/\\\\(\.\[\"uploader\"\]\)/' | \
            sed "s/ /$(printf '%q' "$SEPARATOR")/g"
`
FORMATTING=\"$FORMATTING\"
# echo URL: $URL
# echo SEPARATOR: $SEPARATOR
# echo FORMATTING: "$FORMATTING"
# echo TAGS: $TAGS

#fetching the playlist
PLAYLISTS_CMD="youtube-dl -j --flat-playlist "$URL" | jq -r '$FORMATTING'"
eval "$PLAYLISTS_CMD" #TODO change it to something safer